feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 3000
        loggerLevel: full
        requestInterceptors:
          - top.shusheng007.goodsservice.api.FeignTokenInterceptor
  okhttp:
    enabled: true
  circuitbreaker:
    enabled: true

#spring:
#  cloud:
#    loadbalancer:





