server:
  port: 9091

spring:
  application:
    name: goods-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
  data:
    mongodb:
      uri: mongodb://root:ss007@127.0.0.1:27017/
      database: GoodsRepository


services:
  - name: order-service

logging:
  level:
    org.springframework.web: DEBUG


